---
roles:
  - name: geerlingguy.nginx
    version: 2.8.0
  - name: geerlingguy.adminer
    version: 1.3.0
  - name: geerlingguy.composer
    version: 1.7.6
  - name: geerlingguy.nodejs
    version: 5.1.1
  - name: geerlingguy.mysql
    version: 3.3.0
  - name: geerlingguy.php-mysql
    version: 2.1.0
  - name: geerlingguy.php-versions
    version: 4.0.3
  - name: geerlingguy.php-xdebug
    version: 3.0.0
